version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/penchan?schema=public
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - penchan-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=penchan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - penchan-network

volumes:
  postgres_data:
    driver: local

networks:
  penchan-network:
    driver: bridge 