name: Deploy the frontend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfile.frontend
          build-args:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
          push: true
          tags: |
            rohanshrma222/inksync-frontend:latest
            rohanshrma222/inksync-frontend:${{ github.sha }}
